Feat/add chain
engineer-dao/platform pull request #131
Opened 2022-03-04 22:20 UTC by karmabadger

This adds a few functions to frontend/src/utils/metamask.ts so to add and switch chains using pop ups.

2022-03-04 22:21 UTC, karmabadger commented
a few changes/additions to .env would be required. Please check .env.example, Though, the icon urls isn't required.

2022-03-04 22:24 UTC, karmabadger commented
![image](https://user-images.githubusercontent.com/83666608/156849848-ccb95cdb-685c-4070-84dd-713b5b3d6522.png)
![image](https://user-images.githubusercontent.com/83666608/156849887-11a2446f-17cd-4291-bbcc-115a44b9fef9.png)
![image](https://user-images.githubusercontent.com/83666608/156849950-6a758eeb-36d9-456c-aa0c-0a617fdae411.png)

This either adds the network to the wallet if it's not added or switches to it if it's already added. See pictures for more detail.

2022-03-04 22:25 UTC, karmabadger commented
The button has not been styled since I have no idea how the styling works with tailwind CSS and how to contribute on that end. If someone could help on that front, it would be greatly appreciated. Thank you

2022-03-05 12:03 UTC, reisr3 requested changes
Looking good! Just a couple changes and questions.

2022-03-05 12:03 UTC, reisr3 commented on frontend/.env.example
> +REACT_APP_SUPPORTED_CHAIN_NATIVE_CURRENCY_NAME="MATIC"
Should these include the word `DEFAULT`? Might be easier to read.

`REACT_APP_DEFAULT_CURRENCY_NAME`

2022-03-11 01:31 UTC, reisr3 commented
Hey @catmaxi ! Any questions or pushback here? I'd love to see this get merged in - you did great work!

2022-04-04 06:35 UTC, indeavr reviewed
Changes based on @reisr3 feedback. Ready for more general testing :)

2022-05-27 19:55 UTC, deweller commented
Closing this for now since this branch is too out-of-date.

2022-05-27 19:55 UTC, closed without merging