Contracts refactoring
engineer-dao/platform pull request #38
Opened 2022-02-06 09:59 UTC by indeavr

Please carefully review. 
Changes include:
1) using SafeERC20 for IERC20
2) depositPercent per job
3) is Ownable
4) many onlyOwner management functions
5) COMPLETED_TIMEOUT_SECONDS = 7 days
6) Lots of TODO comments and questions for us to discuss. 
7) Some memory improvements

8) paymentTokens is now an array of ERC20
* jobData includes token field
* daoTreasury address included which receives all the DAO_FEEs as ERC20 tokens. 
The DaoTreasury could also be a Vault contract that automatically swaps all ERC20s to a token of our choosing. 
 
9) disputeResolver address introduced 

After you review and approve we need to refactor the tests.

2022-02-06 19:11 UTC, deweller commented
Good work.  I added a few suggestions and a few things the DAO needs to decide.

2022-02-06 19:12 UTC, deweller requested changes
Good work here.  I think it is a good idea to keep the contract tests in sync whenever we change or add something.

2022-02-06 19:12 UTC, deweller commented on contracts/contracts/Job.sol
> +        require(depositPct < BASE_PERCENTAGE, "Minimum payment not provided");
Error should be "Deposit percent is too high"

2022-02-06 19:12 UTC, deweller commented on contracts/contracts/Job.sol
> +    // TODO: "initiateWithdraw" which starts a 24h timer after which "withdraw(jobId)" can be called by onlyOwner()
I think the dispute resolution covers this case, although it does take a fee.

2022-02-06 19:12 UTC, deweller commented on contracts/contracts/Job.sol
> +    // TODO: what if someone sends a token by mistake to this contract ?
I thought about this a bit too.  By allowing arbitrary withdrawals of funds, we create a larger surface area for an attack.  If someone gets the contract private key(s) they could drain both the daoFunds and the daoEscrow if we have an emergency withdrawal function.

I think we should be conservative and just not allow arbitrary ERC20 withdrawals even by the owner.

We might want to add a function to withdraw ETH, though...

2022-02-06 19:12 UTC, deweller commented on contracts/contracts/Job.sol
> +    // TODO: So that people don't have to trust us
These are good.  Some should apply globally (setDefaultDeposit).  Some might apply per job (setResolutionFee).  We should discuss and decide.

I think bounds checking is good for all of them.

2022-02-06 20:25 UTC, indeavr commented on contracts/contracts/Job.sol
> +        uint256 completedTime;
Nah

2022-02-09 21:06 UTC, deweller approved these changes
Great work.

I added additional issues for potential next steps so we can discuss and/or implement them one and a time.

Ack on merging this.

2022-02-09 21:06 UTC, deweller commented on contracts/contracts/Job.sol
> +            tokensList.push(token);
Created #52

2022-02-09 21:06 UTC, deweller commented on contracts/contracts/Job.sol
> +    // TODO: So that people don't have to trust us
Created issue #53

2022-02-09 21:17 UTC, indeavr commented on contracts/contracts/Job.sol
> +            tokensList.push(token);
lol, Good catch !

2022-02-09 21:22 UTC, reisr3 approved these changes

2022-02-09 21:25 UTC, merged